# Generated by Django 6.0 on 2026-01-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouphierarchy',
            options={'verbose_name_plural': 'Group hierarchies'},
        ),
    ]
