# Generated by Django 6.0 on 2026-01-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Publish'), ('Submit', 'Submit')], default='Draft', max_length=20),
        ),
    ]
